// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection for advisory locks; the app's
    // own runtime client (src/lib/prisma.ts) uses DATABASE_URL (pooled) independently.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
